// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDsGipCfw8CI_zFJD1C5SNhJpi64Yju9s',
    appId: '1:1093419340129:web:e58ba441a21cc514dc7520',
    messagingSenderId: '1093419340129',
    projectId: 'mangxahoi-f31f1',
    authDomain: 'mangxahoi-f31f1.firebaseapp.com',
    storageBucket: 'mangxahoi-f31f1.firebasestorage.app',
    measurementId: 'G-WWE9R6LSG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoSTASzL7Lk3PapatHCL7loH2H_WPLMjQ',
    appId: '1:1093419340129:android:539ebfd5934c5802dc7520',
    messagingSenderId: '1093419340129',
    projectId: 'mangxahoi-f31f1',
    storageBucket: 'mangxahoi-f31f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9GpzUr09wfp1AHRDftkUDeuLan3Ij2cA',
    appId: '1:1093419340129:ios:d545ea00ab2be4ecdc7520',
    messagingSenderId: '1093419340129',
    projectId: 'mangxahoi-f31f1',
    storageBucket: 'mangxahoi-f31f1.firebasestorage.app',
    iosClientId: '1093419340129-ua4134cq12uai76fl3t94qlrmi9ambug.apps.googleusercontent.com',
    iosBundleId: 'com.example.mangxahoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9GpzUr09wfp1AHRDftkUDeuLan3Ij2cA',
    appId: '1:1093419340129:ios:d545ea00ab2be4ecdc7520',
    messagingSenderId: '1093419340129',
    projectId: 'mangxahoi-f31f1',
    storageBucket: 'mangxahoi-f31f1.firebasestorage.app',
    iosClientId: '1093419340129-ua4134cq12uai76fl3t94qlrmi9ambug.apps.googleusercontent.com',
    iosBundleId: 'com.example.mangxahoi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDsGipCfw8CI_zFJD1C5SNhJpi64Yju9s',
    appId: '1:1093419340129:web:e8fa58cb0794e503dc7520',
    messagingSenderId: '1093419340129',
    projectId: 'mangxahoi-f31f1',
    authDomain: 'mangxahoi-f31f1.firebaseapp.com',
    storageBucket: 'mangxahoi-f31f1.firebasestorage.app',
    measurementId: 'G-VWGEM34WX4',
  );
}